#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x17280A9781186ACF (mathieu.desnoyers@efficios.com)
#
Name     : lttng-ust
Version  : 2.10.5
Release  : 1
URL      : http://lttng.org/files/lttng-ust/lttng-ust-2.10.5.tar.bz2
Source0  : http://lttng.org/files/lttng-ust/lttng-ust-2.10.5.tar.bz2
Source1 : http://lttng.org/files/lttng-ust/lttng-ust-2.10.5.tar.bz2.asc
Summary  : The LTTng Userspace Tracer (UST) is a library accompanied by a set of tools to trace userspace code.
Group    : Development/Tools
License  : LGPL-2.1
Requires: lttng-ust-bin = %{version}-%{release}
Requires: lttng-ust-lib = %{version}-%{release}
Requires: lttng-ust-license = %{version}-%{release}
Requires: lttng-ust-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-cmake
BuildRequires : grep
BuildRequires : pkgconfig(liburcu)
BuildRequires : sed
BuildRequires : xmlto

%description
liblttng-ust-libc is used for instrumenting some calls to libc in a
program, without need for recompiling it.

%package bin
Summary: bin components for the lttng-ust package.
Group: Binaries
Requires: lttng-ust-license = %{version}-%{release}

%description bin
bin components for the lttng-ust package.


%package dev
Summary: dev components for the lttng-ust package.
Group: Development
Requires: lttng-ust-lib = %{version}-%{release}
Requires: lttng-ust-bin = %{version}-%{release}
Provides: lttng-ust-devel = %{version}-%{release}
Requires: lttng-ust = %{version}-%{release}

%description dev
dev components for the lttng-ust package.


%package doc
Summary: doc components for the lttng-ust package.
Group: Documentation
Requires: lttng-ust-man = %{version}-%{release}

%description doc
doc components for the lttng-ust package.


%package lib
Summary: lib components for the lttng-ust package.
Group: Libraries
Requires: lttng-ust-license = %{version}-%{release}

%description lib
lib components for the lttng-ust package.


%package license
Summary: license components for the lttng-ust package.
Group: Default

%description license
license components for the lttng-ust package.


%package man
Summary: man components for the lttng-ust package.
Group: Default

%description man
man components for the lttng-ust package.


%prep
%setup -q -n lttng-ust-2.10.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569518024
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1569518024
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lttng-ust
cp COPYING %{buildroot}/usr/share/package-licenses/lttng-ust/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lttng-gen-tp

%files dev
%defattr(-,root,root,-)
/usr/include/lttng/align.h
/usr/include/lttng/bug.h
/usr/include/lttng/lttng-ust-tracef.h
/usr/include/lttng/lttng-ust-tracelog.h
/usr/include/lttng/ringbuffer-abi.h
/usr/include/lttng/ringbuffer-config.h
/usr/include/lttng/tracef.h
/usr/include/lttng/tracelog.h
/usr/include/lttng/tracepoint-event.h
/usr/include/lttng/tracepoint-rcu.h
/usr/include/lttng/tracepoint-types.h
/usr/include/lttng/tracepoint.h
/usr/include/lttng/ust-abi.h
/usr/include/lttng/ust-clock.h
/usr/include/lttng/ust-compiler.h
/usr/include/lttng/ust-config.h
/usr/include/lttng/ust-ctl.h
/usr/include/lttng/ust-elf.h
/usr/include/lttng/ust-endian.h
/usr/include/lttng/ust-error.h
/usr/include/lttng/ust-events.h
/usr/include/lttng/ust-getcpu.h
/usr/include/lttng/ust-tracepoint-event-nowrite.h
/usr/include/lttng/ust-tracepoint-event-reset.h
/usr/include/lttng/ust-tracepoint-event-write.h
/usr/include/lttng/ust-tracepoint-event.h
/usr/include/lttng/ust-tracer.h
/usr/include/lttng/ust-version.h
/usr/include/lttng/ust.h
/usr/lib64/liblttng-ust-ctl.so
/usr/lib64/liblttng-ust-cyg-profile-fast.so
/usr/lib64/liblttng-ust-cyg-profile.so
/usr/lib64/liblttng-ust-dl.so
/usr/lib64/liblttng-ust-fd.so
/usr/lib64/liblttng-ust-fork.so
/usr/lib64/liblttng-ust-libc-wrapper.so
/usr/lib64/liblttng-ust-pthread-wrapper.so
/usr/lib64/liblttng-ust-tracepoint.so
/usr/lib64/liblttng-ust.so
/usr/lib64/pkgconfig/lttng-ust.pc
/usr/share/man/man3/do_tracepoint.3
/usr/share/man/man3/lttng-ust-cyg-profile.3
/usr/share/man/man3/lttng-ust-dl.3
/usr/share/man/man3/lttng-ust.3
/usr/share/man/man3/tracef.3
/usr/share/man/man3/tracelog.3
/usr/share/man/man3/tracepoint.3
/usr/share/man/man3/tracepoint_enabled.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/lttng\-ust/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblttng-ust-ctl.so.4
/usr/lib64/liblttng-ust-ctl.so.4.0.0
/usr/lib64/liblttng-ust-cyg-profile-fast.so.0
/usr/lib64/liblttng-ust-cyg-profile-fast.so.0.0.0
/usr/lib64/liblttng-ust-cyg-profile.so.0
/usr/lib64/liblttng-ust-cyg-profile.so.0.0.0
/usr/lib64/liblttng-ust-dl.so.0
/usr/lib64/liblttng-ust-dl.so.0.0.0
/usr/lib64/liblttng-ust-fd.so.0
/usr/lib64/liblttng-ust-fd.so.0.0.0
/usr/lib64/liblttng-ust-fork.so.0
/usr/lib64/liblttng-ust-fork.so.0.0.0
/usr/lib64/liblttng-ust-libc-wrapper.so.0
/usr/lib64/liblttng-ust-libc-wrapper.so.0.0.0
/usr/lib64/liblttng-ust-pthread-wrapper.so.0
/usr/lib64/liblttng-ust-pthread-wrapper.so.0.0.0
/usr/lib64/liblttng-ust-tracepoint.so.0
/usr/lib64/liblttng-ust-tracepoint.so.0.0.0
/usr/lib64/liblttng-ust.so.0
/usr/lib64/liblttng-ust.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lttng-ust/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lttng-gen-tp.1
