#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: da8b975
#
# Source0 file verified with key 0x17280A9781186ACF (mathieu.desnoyers@efficios.com)
#
Name     : lttng-ust
Version  : 2.12.9
Release  : 22
URL      : http://lttng.org/files/lttng-ust/lttng-ust-2.12.9.tar.bz2
Source0  : http://lttng.org/files/lttng-ust/lttng-ust-2.12.9.tar.bz2
Source1  : http://lttng.org/files/lttng-ust/lttng-ust-2.12.9.tar.bz2.asc
Summary  : The LTTng Userspace Tracer (UST) is a library accompanied by a set of tools to trace userspace code.
Group    : Development/Tools
License  : LGPL-2.1 MIT
Requires: lttng-ust-bin = %{version}-%{release}
Requires: lttng-ust-lib = %{version}-%{release}
Requires: lttng-ust-license = %{version}-%{release}
Requires: lttng-ust-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-configure
BuildRequires : cmake
BuildRequires : grep
BuildRequires : numactl-dev
BuildRequires : pkgconfig(liburcu)
BuildRequires : sed
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
liblttng-ust-libc is used for instrumenting some calls to libc in a
program, without need for recompiling it.

%package bin
Summary: bin components for the lttng-ust package.
Group: Binaries
Requires: lttng-ust-license = %{version}-%{release}

%description bin
bin components for the lttng-ust package.


%package dev
Summary: dev components for the lttng-ust package.
Group: Development
Requires: lttng-ust-lib = %{version}-%{release}
Requires: lttng-ust-bin = %{version}-%{release}
Provides: lttng-ust-devel = %{version}-%{release}
Requires: lttng-ust = %{version}-%{release}

%description dev
dev components for the lttng-ust package.


%package doc
Summary: doc components for the lttng-ust package.
Group: Documentation
Requires: lttng-ust-man = %{version}-%{release}

%description doc
doc components for the lttng-ust package.


%package lib
Summary: lib components for the lttng-ust package.
Group: Libraries
Requires: lttng-ust-license = %{version}-%{release}

%description lib
lib components for the lttng-ust package.


%package license
Summary: license components for the lttng-ust package.
Group: Default

%description license
license components for the lttng-ust package.


%package man
Summary: man components for the lttng-ust package.
Group: Default

%description man
man components for the lttng-ust package.


%prep
%setup -q -n lttng-ust-2.12.9
cd %{_builddir}/lttng-ust-2.12.9
pushd ..
cp -a lttng-ust-2.12.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1708645828
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1708645828
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lttng-ust
cp %{_builddir}/lttng-ust-%{version}/COPYING %{buildroot}/usr/share/package-licenses/lttng-ust/0f56d2f61ba79579aacae13e71912816207b9f92 || :
cp %{_builddir}/lttng-ust-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/lttng-ust/29343e0b8f4b075479f81da0f459e1c5e56cc9d0 || :
cp %{_builddir}/lttng-ust-%{version}/mit-license.txt %{buildroot}/usr/share/package-licenses/lttng-ust/896db08d9336fddb884ddd3994bd28993200ea1a || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lttng-gen-tp

%files dev
%defattr(-,root,root,-)
/usr/include/lttng/align.h
/usr/include/lttng/bug.h
/usr/include/lttng/lttng-ust-tracef.h
/usr/include/lttng/lttng-ust-tracelog.h
/usr/include/lttng/ringbuffer-abi.h
/usr/include/lttng/ringbuffer-config.h
/usr/include/lttng/tracef.h
/usr/include/lttng/tracelog.h
/usr/include/lttng/tracepoint-event.h
/usr/include/lttng/tracepoint-rcu.h
/usr/include/lttng/tracepoint-types.h
/usr/include/lttng/tracepoint.h
/usr/include/lttng/ust-abi.h
/usr/include/lttng/ust-clock.h
/usr/include/lttng/ust-compiler.h
/usr/include/lttng/ust-config.h
/usr/include/lttng/ust-ctl.h
/usr/include/lttng/ust-elf.h
/usr/include/lttng/ust-endian.h
/usr/include/lttng/ust-error.h
/usr/include/lttng/ust-events.h
/usr/include/lttng/ust-getcpu.h
/usr/include/lttng/ust-tracepoint-event-nowrite.h
/usr/include/lttng/ust-tracepoint-event-reset.h
/usr/include/lttng/ust-tracepoint-event-write.h
/usr/include/lttng/ust-tracepoint-event.h
/usr/include/lttng/ust-tracer.h
/usr/include/lttng/ust-version.h
/usr/include/lttng/ust.h
/usr/lib64/liblttng-ust-ctl.so
/usr/lib64/liblttng-ust-cyg-profile-fast.so
/usr/lib64/liblttng-ust-cyg-profile.so
/usr/lib64/liblttng-ust-dl.so
/usr/lib64/liblttng-ust-fd.so
/usr/lib64/liblttng-ust-fork.so
/usr/lib64/liblttng-ust-libc-wrapper.so
/usr/lib64/liblttng-ust-pthread-wrapper.so
/usr/lib64/liblttng-ust-tracepoint.so
/usr/lib64/liblttng-ust.so
/usr/lib64/pkgconfig/lttng-ust-ctl.pc
/usr/lib64/pkgconfig/lttng-ust.pc
/usr/share/man/man3/do_tracepoint.3
/usr/share/man/man3/lttng-ust-cyg-profile.3
/usr/share/man/man3/lttng-ust-dl.3
/usr/share/man/man3/lttng-ust.3
/usr/share/man/man3/tracef.3
/usr/share/man/man3/tracelog.3
/usr/share/man/man3/tracepoint.3
/usr/share/man/man3/tracepoint_enabled.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/lttng\-ust/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/liblttng-ust-ctl.so.4.0.0
/V3/usr/lib64/liblttng-ust-cyg-profile-fast.so.0.0.0
/V3/usr/lib64/liblttng-ust-cyg-profile.so.0.0.0
/V3/usr/lib64/liblttng-ust-dl.so.0.0.0
/V3/usr/lib64/liblttng-ust-fd.so.0.0.0
/V3/usr/lib64/liblttng-ust-fork.so.0.0.0
/V3/usr/lib64/liblttng-ust-libc-wrapper.so.0.0.0
/V3/usr/lib64/liblttng-ust-pthread-wrapper.so.0.0.0
/V3/usr/lib64/liblttng-ust-tracepoint.so.0.0.0
/V3/usr/lib64/liblttng-ust.so.0.0.0
/usr/lib64/liblttng-ust-ctl.so.4
/usr/lib64/liblttng-ust-ctl.so.4.0.0
/usr/lib64/liblttng-ust-cyg-profile-fast.so.0
/usr/lib64/liblttng-ust-cyg-profile-fast.so.0.0.0
/usr/lib64/liblttng-ust-cyg-profile.so.0
/usr/lib64/liblttng-ust-cyg-profile.so.0.0.0
/usr/lib64/liblttng-ust-dl.so.0
/usr/lib64/liblttng-ust-dl.so.0.0.0
/usr/lib64/liblttng-ust-fd.so.0
/usr/lib64/liblttng-ust-fd.so.0.0.0
/usr/lib64/liblttng-ust-fork.so.0
/usr/lib64/liblttng-ust-fork.so.0.0.0
/usr/lib64/liblttng-ust-libc-wrapper.so.0
/usr/lib64/liblttng-ust-libc-wrapper.so.0.0.0
/usr/lib64/liblttng-ust-pthread-wrapper.so.0
/usr/lib64/liblttng-ust-pthread-wrapper.so.0.0.0
/usr/lib64/liblttng-ust-tracepoint.so.0
/usr/lib64/liblttng-ust-tracepoint.so.0.0.0
/usr/lib64/liblttng-ust.so.0
/usr/lib64/liblttng-ust.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lttng-ust/0f56d2f61ba79579aacae13e71912816207b9f92
/usr/share/package-licenses/lttng-ust/29343e0b8f4b075479f81da0f459e1c5e56cc9d0
/usr/share/package-licenses/lttng-ust/896db08d9336fddb884ddd3994bd28993200ea1a

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lttng-gen-tp.1
